### ISSUE TITLE
sha2-256 is still missing for some assets

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-api#254]
detected while eyeballing backup2datalad progress which had
```
2021-04-29T10:13:52-0400 [INFO    ] backups2datalad.py Syncing asset sub-YutaMouse33/sub-YutaMouse33_ses-YutaMouse33-150219_behavior+ecephys.nwb
2021-04-29T10:13:52-0400 [WARNING ] backups2datalad.py Asset metadata does not include sha256 hash
2021-04-29T10:13:53-0400 [INFO    ] backups2datalad.py Asset in dataset, and etag shows no modification; will not update
```

e.g. missing for 
```shell
$> curl --silent -X GET "https://api.dandiarchive.org/api/dandisets/000003/versions/draft/assets/388cfd71-e47c-4c0f-b443-bec358530a15/" -H "accept: application/json" | jq '.digest'
{
  "dandi:dandi-etag": "be4ba04a886d7de3e76033c35983f4b8-292"
}
```
while present for "neighboring" asset
```shell
$> curl --silent -X GET "https://api.dandiarchive.org/api/dandisets/000003/versions/draft/assets/8d21b488-9663-4816-8ff5-decc45591353/" -H "accept: application/json" | jq '.digest'             
{
  "dandi:dandi-etag": "3e0ec161bae64cd30918d5fabf7cf66a-178",
  "dandi:sha2-256": "8307d17af64ad5a2355feeda58c6febad94a63447ff6c84acd769675536caa9d"
}
```

FWIW: it is not a single case -- a few other assets from 000003 are missing it too

**Comment by yarikoptic** [comment]
remains the case:
```
$> dandi ls -f json_pp --metadata assets dandi://dandi/000003/sub-YutaMouse33/sub-YutaMouse33_ses-YutaMouse33-150219_behavior+ecephys.nwb | jq '.[].metadata["digest"]'              
2021-07-06 08:38:33,842 [    INFO] Logs saved in /home/yoh/.cache/dandi-cli/log/20210706123832Z-1563001.log
{
  "dandi:dandi-etag": "be4ba04a886d7de3e76033c35983f4b8-292"
}
```
@dchiquito - could you please investigate why some assets might still be missing sha256 and trigger this digest estimation for them?

**Comment by waxlamp** [comment]
I have a feeling this has been solved.

**Comment by satra** [comment]
this one should be a nagios type check on the database because this is a background process that could fail and we would only know it based on dandiset validation errors. this can remain closed, but we should work towards the state of the archive dashboard.

**Comment by yarikoptic** [comment]
I have a feeling it was not solved.  My feeling is supported by running the original cmdline invocation:
```
$> dandi ls -f json_pp --metadata assets dandi://dandi/000003/sub-YutaMouse33/sub-YutaMouse33_ses-YutaMouse33-150219_behavior+ecephys.nwb | jq '.[].metadata["digest"]'
2021-07-17 11:13:00,182 [    INFO] Logs saved in /home/yoh/.cache/dandi-cli/log/20210717151258Z-3169561.log
{
  "dandi:dandi-etag": "be4ba04a886d7de3e76033c35983f4b8-292"
}
```

What supported your feeling @waxlamp ?

**Comment by waxlamp** [comment]
> What supported your feeling @waxlamp ?

Admittedly, not much. I just assumed that missing digests would be a bigger problem that would have forced a fix by now.

I see a few things to do here:
- create a route for a dandiset owner to offer a digest value if one is missing, to be validated by the server (or, if this doesn't make sense, simply to compute and save the digest during validation if it is missing)
- write a one-time repair script that will go through the existing assets and force a recomputation of the digests
- add UI to indicate missing digests, and suggest what to do (I guess this is connected to bullet point 0 above)

Can you advise on which, if any, of these bullet points is appropriate for us to take on?

**Comment by satra** [comment]
most of the missing digests are because the hash computation process on the api server failed for some reason. the server should automatically relaunch these jobs. (and the number/location of such failures can be monitored on our dashboard).

the hash recomputation only needs to happen on assets missing them, so could be triggered by a cron job. instead of a user contacting us, it would be good for our internal dashboards to indicate such failures. (i simply went through the validation endpoint to find them, so should be even easier internally).

**Comment by satra** [comment]
bumping this for more urgency. this prevents publish on dandisets, and nothing an owner can do, since this is a server side operation.

**Comment by dchiquito** [comment]
I manually triggered recomputation, it's been going for a few hours now. It looks like the assets with problems were mostly large, so hopefully recomputation will be done tomorrow.

**Comment by yarikoptic** [comment]
hm, I thought I posted a question but apparently not:

- will we/you be notified whenever triggered recomputation (I hope only on blobs which lacked sha2-256, not all) errors out?

FWIW, in the past 24 hours there were many (>250) "heroku[worker.1]: Error R14 (Memory quota exceeded)" logged (ref: #133).

**Comment by dchiquito** [comment]
We should get alerts in Sentry in the event of failures.

The heroku warnings occur when the 1GB RAM quota is full. There is also 1GB of swap space to tap into, so nothing actually breaks until the application hits 2GB of memory in use. 

The jobs have completed and there are no more blobs with undefined sha256 checksums, so I'm going to close this issue and open a new one to monitor for this happening in the future.
